Yggdrasil/new content0
Solaestas/Everglow pull request #195
Opened 2023-06-21 07:06 UTC by Omnielement

Random terrain generation. and some new changes.

2023-06-22 00:47 UTC, Setnour6 commented
Upon testing, only the origin pylon, tiles underneath it, and the lowest level of the Yggdrasil were generated, but almost empty. A lot of the content has been removed though, so I'll wait until it comes back.
Other than that, the effects for the origin pylon look really nice. Maybe it can be used as a way to teleport to other pylons or orbs in the Yggdrasil.

2023-07-21 20:14 UTC, Setnour6 requested changes
I tested it again. I thought there would be more updates or changes. I assume this is finished for now.

When I am at 735' Surface or higher and I am in the Kelp Curtain biome, the kelp curtain music players as normal. But when I am below 734' or lower, the Yggdrasil Town/Mines theme plays.
![image](https://github.com/Solaestas/Everglow/assets/70764728/36ce1190-2af1-4564-8dfd-a6de960b3b2d)
![image](https://github.com/Solaestas/Everglow/assets/70764728/81206c1a-3388-4f86-bffe-442ffec391cf)
Note the water color change and the depth meter number.

The level or height from the music change needs to be lower.
![image](https://github.com/Solaestas/Everglow/assets/70764728/902aa058-fed1-4600-8707-7d4d19db976b)
Around 615' Surface should be good.

That is all that needs to change. Everything else can be done in future commits.

2023-07-21 22:09 UTC, Setnour6 approved these changes
Nevermind, I decided to make the change myself.
This PR is good to go.
if merged or synced with master, we need to close #204.

2023-08-29 19:06 UTC, Setnour6 requested changes
With the new content and changes made, I find that there are some things that need to be changed more.

- Squamous Shell needs movement sprites and proper sprites for flying. Currently the flying sprites are based on the old squamous shell sprites.
- The Stone Cage of Challenges backgrounds and objects has a couple of position issues. I circled them in red. **(fixed)**
![image](https://github.com/Solaestas/Everglow/assets/70764728/6ba3ebfb-fee9-4dbb-848a-011205f502a4)

- The Yggdrasil Amber tile needs an outline so people can see it better. **(fixed)**
![image](https://github.com/Solaestas/Everglow/assets/70764728/dc02eaf8-ebef-4e43-a819-09e28028b700)

- The Squamous Seal still does not show. **(fixed)**
![image](https://github.com/Solaestas/Everglow/assets/70764728/9c484b7f-2454-42d9-9d80-9d4fa636f124)

- The background change to stone cage of challenges shows that it instantly changes. It might be better if you add more tiles at the entrance to cover it up.
![dotnet_sd1I4dYus5](https://github.com/Solaestas/Everglow/assets/70764728/d8d35348-6a83-430a-9558-01d49cbbb53c)


![YGGDRASIL CAGE BEFORE](https://github.com/Solaestas/Everglow/assets/70764728/1eca993e-aab7-4605-87be-8051cf323e9c)
![YGGDRASIL CAGE AFTER](https://github.com/Solaestas/Everglow/assets/70764728/63e81b01-6228-4a6d-8f83-f1d2c9423ad5)

There is still a projectile hitbox after the rock spike explodes. It can hurt players unfairly (I spawned it in myself and it doesn't do damage to me but it will when Squamous Shell spawns it).
![dotnet_cq1S2nV7id](https://github.com/Solaestas/Everglow/assets/70764728/7c5c9188-c179-4dd2-abaa-dc633902d8c6)


### Ideas that are not part of review

- A line to travel on (zip line? zipline?) that takes you to the stone cage of challenges
        - Alternative: an item that launches a grappling hook (but needs to be charged/channeled to use)
        - Alternative: generate minecart rails that lead to the stone cage of challenges.
        - Alternative: anything else that you prefer

2023-10-17 13:28 UTC, Setnour6 commented
Going to try something

2024-04-07 13:20 UTC, Omnielement commented
Too much contents had been add in this branch.Conflict potention increased day by day.Try to test, find bugs, and merge soon.

2024-04-10 12:03 UTC, Felixyang777 approved these changes

2024-04-13 10:37 UTC, Omnielement commented
Update log.
[Uploading UpdateLogs.docx…]()

2024-04-13 10:40 UTC, Omnielement commented
Update log.
[UpdateLogs.docx](https://github.com/Solaestas/Everglow/files/14967096/UpdateLogs.docx)

2024-04-13 15:23 UTC, Setnour6 approved these changes

2024-04-13 15:24 UTC, Setnour6 commented
It was approved before but it got blocked by the earlier requesting changes. I'll double check the new changes in the game to make sure it works properly

2024-04-13 17:36 UTC, Setnour6 requested changes
I just tested it again and there is only a couple of things I noticed
### Requests
**World**:
- Teleporting to or going up to the top left causes a stack overflow error.
![image](https://github.com/Solaestas/Everglow/assets/70764728/c06619f4-bd3e-4316-9838-fa26980d4cf0)
client.log: [client.log](https://github.com/Solaestas/Everglow/files/14968092/client.log)

### Concerns
**World**:
- The current Yggdrasil world doesn't look as explorable or easy to navigate as I thought it would be. Didn't you want the player to start there first at one point?
![image](https://github.com/Solaestas/Everglow/assets/70764728/bdc7138d-ca17-4392-bad1-c4ffd3b58282)
- There is no area for Squamous Shell to spawn anymore. Where should we put it?

**I will update this message if needed**

2024-04-17 01:23 UTC, Setnour6 approved these changes
I tested it again by creating a new world and the stack overflow issue fixed itself. We can wait for Felix to finish the changes he wants to make, or we can merge now and have Felix carry the changes to newContent1 or for him keep working on newContent0.

2024-04-17 09:43 UTC, merged