Minortopography/genpass
Solaestas/Everglow pull request #216
Opened 2023-08-19 14:28 UTC by Omnielement

add giant pine tree

2023-08-19 17:03 UTC, Setnour6 commented on Sources/Modules/Minortopography/GiantPinetree/Items/HarvestingClaw.cs
> +		return base.Shoot(player, source, position, velocity, type, damage, knockback);
When In tested this, the right click function does the same thing as the left click function but without auto use. How come there is no Item.shoot or other function for shoot?

2023-08-19 17:40 UTC, Setnour6 commented on Sources/Modules/Minortopography/GiantPinetree/Projectiles/PineSprite.png
The sprite should have a different sprite/image/texture. It does not look proper in appearance as just a green box.
![image](https://github.com/Solaestas/Everglow/assets/70764728/dacb77bb-9b3e-4162-8992-b2b75b47da62)
You can still keep it as an extra sprite for highlighting the hostile NPCs. I will let you decide

2023-08-19 17:40 UTC, Setnour6 commented on Sources/Modules/Minortopography/GiantPinetree/Items/CreatPineTree.cs
This creates the giant pine cones and chest but not any trees

2023-08-19 17:40 UTC, Setnour6 commented on Sources/Modules/Minortopography/GiantPinetree/Items/SungloChandelier.cs
The animation for the chandelier does not work properly
![image](https://github.com/Solaestas/Everglow/assets/70764728/b223fe6a-a883-435c-8b6d-89e35e57640d)
Mining it also makes the game freeze/crash and closes the game.

2023-08-19 17:50 UTC, Setnour6 requested changes
So what needs to change is
- Iced Spear hurting town NPCs
- the pine sprite
- the sunglow chandelier's animation being broken
- mining the sunglow chandelier crashes the game

2023-08-20 15:17 UTC, Omnielement commented
@Setnour6 What are you doing in IcedSpear(Projectile)? "Collide" is using to detect NPC, it's not a vanilla method.

2023-08-20 15:38 UTC, Setnour6 commented
> @Setnour6 What are you doing in IcedSpear(Projectile)? "Collide" is using to detect NPC, it's not a vanilla method.

There is an issue when I point the spear to the ground on a lower surface area and the spear is touching the ground. I wanted to fix that.
![dotnet_IFbqBr1ifX](https://github.com/Solaestas/Everglow/assets/70764728/f2905945-1d20-4169-8a2e-2cafd3f34e80)

2023-08-20 15:46 UTC, Omnielement commented
> > @Setnour6 What are you doing in IcedSpear(Projectile)? "Collide" is using to detect NPC, it's not a vanilla method.
> 
> There is an issue when I point the spear to the ground on a lower surface area and the spear is touching the ground. I wanted to fix that. ![dotnet_IFbqBr1ifX](https://user-images.githubusercontent.com/70764728/261861716-f2905945-1d20-4169-8a2e-2cafd3f34e80.gif)

Can it still stick to the target normally now?

2023-08-20 15:53 UTC, Setnour6 commented
> Can it still stick to the target normally now?

It looks like it can
![dotnet_udZ0dNiZQ3](https://github.com/Solaestas/Everglow/assets/70764728/54241ca9-ab2f-4925-aeea-7ae37c131f05)

2023-08-20 15:55 UTC, Omnielement commented
> > Can it still stick to the target normally now?
> 
> It looks like it can ![dotnet_udZ0dNiZQ3](https://user-images.githubusercontent.com/70764728/261862537-54241ca9-ab2f-4925-aeea-7ae37c131f05.gif)

I apologize, I was misunderstood your code.Everything was well, you can revert the "undo".

2023-08-20 15:58 UTC, Setnour6 commented
> I apologize, I was misunderstood your code.Everything was well, you can revert the "undo".

That is okay. I know you wanted the collision functions to work properly and I do too

2023-08-22 14:06 UTC, Setnour6 commented
I tested it. The last thing that needs to change is the sunglow chandelier animation not working, and that's it.
Also, is the pine sprite supposed to attack enemies or does it just hover over them to highlight them?

2023-08-24 09:29 UTC, merged

2023-08-24 09:30 UTC, Omnielement commented
this branch still very important after this merge