能进联机了，但不能保证以后。说实话，我认为需要重新写所有的资源加载和初始化...
Solaestas/Everglow pull request #255
Opened 2024-04-03 13:16 UTC by shb201902040125

我不敢细究到底有多少初始化和资源加载是有问题的。目前的情况来看，实例化时候直接取用一些潜在为null的对象，或者再SetDefaults中直接加载资源不是近期才有的事情。
只能说目前应该能够进入联机模式了，但无法保证其他潜在的问题。甚至我怀疑联机的同步也会存在问题
尽快进行审核，至少获得3人通过。审核后请务必留言
I dare not go into the details of how many initializations and resource loads are problematic. As it stands, fetching potentially null objects directly during instantiation, or directly loading resources in SetDefaults, is not a recent thing.
Can only say that the current should be able to enter online mode, but can not guarantee other potential problems. Even I suspect there will be problems with online synchronization
Audit as soon as possible, at least 3 people pass. Please be sure to leave a message after review

2024-04-04 09:24 UTC, Omnielement approved these changes

2024-04-04 10:56 UTC, Omnielement commented
可以和其他人进入游戏，但是不能去子世界。

2024-04-04 10:58 UTC, Solaestas requested changes
等我来改吧，很多操作有问题

2024-04-11 17:39 UTC, Setnour6 commented
I tested this with an alternate account and found that many weapons and projectiles are not showing or synchronized to the other players in multiplayer. One example of this is the Chocolate Cream Cup Staff's right click cream projectile not showing up for the other user when the use time/animation for it is complete.

2026-05-09 01:30 UTC, closed without merging